Updates for composite workflow https://app.asana.com/0/inbox/1199715509913347/1200914093450351

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -33,8 +33,19 @@ inputs:
     description: "Exit code for reviewdog when errors are found [true,false]."
     default: 'false'
 runs:
-  using: 'docker'
-  image: 'Dockerfile'
+  using: composite
+    - run: |
+        export INPUT_GITHUB_TOKEN=${{ inputs.github_token }};
+        FILEPATH="${{ github.action_path }}/entrypoint.sh"
+        if [ -f "$FILEPATH" ]; then
+          chmod +x $FILEPATH
+          $FILEPATH
+        else
+          # Exit as not found ( in bash exit code )
+          exit 127
+        fi
+      shell: bash
+  
 branding:
   icon: 'edit'
   color: 'gray-dark'
